// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqs878HwKucREDuLPdAqhcxqZ8hlApsqk',
    appId: '1:1063772694138:web:7bf52bd3c6dc856981fdc3',
    messagingSenderId: '1063772694138',
    projectId: 'khushhal-kisan-app',
    authDomain: 'khushhal-kisan-app.firebaseapp.com',
    storageBucket: 'khushhal-kisan-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtRA5ArClxmIil-WecLpVLvYajjd_a910',
    appId: '1:1063772694138:android:a38e3f70bab49e1881fdc3',
    messagingSenderId: '1063772694138',
    projectId: 'khushhal-kisan-app',
    storageBucket: 'khushhal-kisan-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbt1ExfgHkc9pz1Ho7ZaIAitrW6QlbMQ0',
    appId: '1:1063772694138:ios:d5e4e9bc41fa8a1781fdc3',
    messagingSenderId: '1063772694138',
    projectId: 'khushhal-kisan-app',
    storageBucket: 'khushhal-kisan-app.firebasestorage.app',
    iosBundleId: 'com.example.khushhalKisanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqs878HwKucREDuLPdAqhcxqZ8hlApsqk',
    appId: '1:1063772694138:web:5636a7aea096484e81fdc3',
    messagingSenderId: '1063772694138',
    projectId: 'khushhal-kisan-app',
    authDomain: 'khushhal-kisan-app.firebaseapp.com',
    storageBucket: 'khushhal-kisan-app.firebasestorage.app',
  );
}
